//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CapaSOA2GJ.refFacade2GJBA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Facade2GJBASoap", Namespace="Facade2GJ")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Facade2GJBA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QryXMLStrByALOperationCompleted;
        
        private System.Threading.SendOrPostCallback QryXMLStrByDSOperationCompleted;
        
        private System.Threading.SendOrPostCallback QryXMLStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback QryFastStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback QryFastStrByDSOperationCompleted;
        
        private System.Threading.SendOrPostCallback EjectAsyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback EjectAsyncNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingFacadeQryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Facade2GJBA() {
            this.Url = global::CapaSOA2GJ.Properties.Settings.Default.CapaSOA2GJ_refFacade2GJBA_Facade2GJBA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QryXMLStrByALCompletedEventHandler QryXMLStrByALCompleted;
        
        /// <remarks/>
        public event QryXMLStrByDSCompletedEventHandler QryXMLStrByDSCompleted;
        
        /// <remarks/>
        public event QryXMLStrCompletedEventHandler QryXMLStrCompleted;
        
        /// <remarks/>
        public event QryFastStrCompletedEventHandler QryFastStrCompleted;
        
        /// <remarks/>
        public event QryFastStrByDSCompletedEventHandler QryFastStrByDSCompleted;
        
        /// <remarks/>
        public event EjectAsyncCompletedEventHandler EjectAsyncCompleted;
        
        /// <remarks/>
        public event EjectAsyncNewCompletedEventHandler EjectAsyncNewCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event PingFacadeQryCompletedEventHandler PingFacadeQryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/QryXMLStrByAL", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] QryXMLStrByAL(string InStr) {
            object[] results = this.Invoke("QryXMLStrByAL", new object[] {
                        InStr});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void QryXMLStrByALAsync(string InStr) {
            this.QryXMLStrByALAsync(InStr, null);
        }
        
        /// <remarks/>
        public void QryXMLStrByALAsync(string InStr, object userState) {
            if ((this.QryXMLStrByALOperationCompleted == null)) {
                this.QryXMLStrByALOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQryXMLStrByALOperationCompleted);
            }
            this.InvokeAsync("QryXMLStrByAL", new object[] {
                        InStr}, this.QryXMLStrByALOperationCompleted, userState);
        }
        
        private void OnQryXMLStrByALOperationCompleted(object arg) {
            if ((this.QryXMLStrByALCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QryXMLStrByALCompleted(this, new QryXMLStrByALCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/QryXMLStrByDS", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QryXMLStrByDS(string InStr) {
            object[] results = this.Invoke("QryXMLStrByDS", new object[] {
                        InStr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QryXMLStrByDSAsync(string InStr) {
            this.QryXMLStrByDSAsync(InStr, null);
        }
        
        /// <remarks/>
        public void QryXMLStrByDSAsync(string InStr, object userState) {
            if ((this.QryXMLStrByDSOperationCompleted == null)) {
                this.QryXMLStrByDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQryXMLStrByDSOperationCompleted);
            }
            this.InvokeAsync("QryXMLStrByDS", new object[] {
                        InStr}, this.QryXMLStrByDSOperationCompleted, userState);
        }
        
        private void OnQryXMLStrByDSOperationCompleted(object arg) {
            if ((this.QryXMLStrByDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QryXMLStrByDSCompleted(this, new QryXMLStrByDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/QryXMLStr", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QryXMLStr(string InStr) {
            object[] results = this.Invoke("QryXMLStr", new object[] {
                        InStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QryXMLStrAsync(string InStr) {
            this.QryXMLStrAsync(InStr, null);
        }
        
        /// <remarks/>
        public void QryXMLStrAsync(string InStr, object userState) {
            if ((this.QryXMLStrOperationCompleted == null)) {
                this.QryXMLStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQryXMLStrOperationCompleted);
            }
            this.InvokeAsync("QryXMLStr", new object[] {
                        InStr}, this.QryXMLStrOperationCompleted, userState);
        }
        
        private void OnQryXMLStrOperationCompleted(object arg) {
            if ((this.QryXMLStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QryXMLStrCompleted(this, new QryXMLStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/QryFastStr", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QryFastStr(string InStr) {
            object[] results = this.Invoke("QryFastStr", new object[] {
                        InStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QryFastStrAsync(string InStr) {
            this.QryFastStrAsync(InStr, null);
        }
        
        /// <remarks/>
        public void QryFastStrAsync(string InStr, object userState) {
            if ((this.QryFastStrOperationCompleted == null)) {
                this.QryFastStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQryFastStrOperationCompleted);
            }
            this.InvokeAsync("QryFastStr", new object[] {
                        InStr}, this.QryFastStrOperationCompleted, userState);
        }
        
        private void OnQryFastStrOperationCompleted(object arg) {
            if ((this.QryFastStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QryFastStrCompleted(this, new QryFastStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/QryFastStrByDS", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QryFastStrByDS(string InStr) {
            object[] results = this.Invoke("QryFastStrByDS", new object[] {
                        InStr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QryFastStrByDSAsync(string InStr) {
            this.QryFastStrByDSAsync(InStr, null);
        }
        
        /// <remarks/>
        public void QryFastStrByDSAsync(string InStr, object userState) {
            if ((this.QryFastStrByDSOperationCompleted == null)) {
                this.QryFastStrByDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQryFastStrByDSOperationCompleted);
            }
            this.InvokeAsync("QryFastStrByDS", new object[] {
                        InStr}, this.QryFastStrByDSOperationCompleted, userState);
        }
        
        private void OnQryFastStrByDSOperationCompleted(object arg) {
            if ((this.QryFastStrByDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QryFastStrByDSCompleted(this, new QryFastStrByDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/EjectAsync", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EjectAsync(int In_IdCase, int In_IdWI, string In_User) {
            object[] results = this.Invoke("EjectAsync", new object[] {
                        In_IdCase,
                        In_IdWI,
                        In_User});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EjectAsyncAsync(int In_IdCase, int In_IdWI, string In_User) {
            this.EjectAsyncAsync(In_IdCase, In_IdWI, In_User, null);
        }
        
        /// <remarks/>
        public void EjectAsyncAsync(int In_IdCase, int In_IdWI, string In_User, object userState) {
            if ((this.EjectAsyncOperationCompleted == null)) {
                this.EjectAsyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEjectAsyncOperationCompleted);
            }
            this.InvokeAsync("EjectAsync", new object[] {
                        In_IdCase,
                        In_IdWI,
                        In_User}, this.EjectAsyncOperationCompleted, userState);
        }
        
        private void OnEjectAsyncOperationCompleted(object arg) {
            if ((this.EjectAsyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EjectAsyncCompleted(this, new EjectAsyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/EjectAsyncNew", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EjectAsyncNew(int In_IdCase, long In_IdWI, string In_User) {
            object[] results = this.Invoke("EjectAsyncNew", new object[] {
                        In_IdCase,
                        In_IdWI,
                        In_User});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EjectAsyncNewAsync(int In_IdCase, long In_IdWI, string In_User) {
            this.EjectAsyncNewAsync(In_IdCase, In_IdWI, In_User, null);
        }
        
        /// <remarks/>
        public void EjectAsyncNewAsync(int In_IdCase, long In_IdWI, string In_User, object userState) {
            if ((this.EjectAsyncNewOperationCompleted == null)) {
                this.EjectAsyncNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEjectAsyncNewOperationCompleted);
            }
            this.InvokeAsync("EjectAsyncNew", new object[] {
                        In_IdCase,
                        In_IdWI,
                        In_User}, this.EjectAsyncNewOperationCompleted, userState);
        }
        
        private void OnEjectAsyncNewOperationCompleted(object arg) {
            if ((this.EjectAsyncNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EjectAsyncNewCompleted(this, new EjectAsyncNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/Ping", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping(string InStr) {
            object[] results = this.Invoke("Ping", new object[] {
                        InStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync(string InStr) {
            this.PingAsync(InStr, null);
        }
        
        /// <remarks/>
        public void PingAsync(string InStr, object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[] {
                        InStr}, this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Facade2GJ/PingFacadeQry", RequestNamespace="Facade2GJ", ResponseNamespace="Facade2GJ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PingFacadeQry(string InStr) {
            object[] results = this.Invoke("PingFacadeQry", new object[] {
                        InStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingFacadeQryAsync(string InStr) {
            this.PingFacadeQryAsync(InStr, null);
        }
        
        /// <remarks/>
        public void PingFacadeQryAsync(string InStr, object userState) {
            if ((this.PingFacadeQryOperationCompleted == null)) {
                this.PingFacadeQryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingFacadeQryOperationCompleted);
            }
            this.InvokeAsync("PingFacadeQry", new object[] {
                        InStr}, this.PingFacadeQryOperationCompleted, userState);
        }
        
        private void OnPingFacadeQryOperationCompleted(object arg) {
            if ((this.PingFacadeQryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingFacadeQryCompleted(this, new PingFacadeQryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void QryXMLStrByALCompletedEventHandler(object sender, QryXMLStrByALCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QryXMLStrByALCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QryXMLStrByALCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void QryXMLStrByDSCompletedEventHandler(object sender, QryXMLStrByDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QryXMLStrByDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QryXMLStrByDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void QryXMLStrCompletedEventHandler(object sender, QryXMLStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QryXMLStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QryXMLStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void QryFastStrCompletedEventHandler(object sender, QryFastStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QryFastStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QryFastStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void QryFastStrByDSCompletedEventHandler(object sender, QryFastStrByDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QryFastStrByDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QryFastStrByDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void EjectAsyncCompletedEventHandler(object sender, EjectAsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EjectAsyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EjectAsyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void EjectAsyncNewCompletedEventHandler(object sender, EjectAsyncNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EjectAsyncNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EjectAsyncNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PingFacadeQryCompletedEventHandler(object sender, PingFacadeQryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingFacadeQryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingFacadeQryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591